---
repos:
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: go-fmt
          - id: go-vet
          - id: go-imports
          - id: go-cyclo
            args: [-over=15, -ignore=.*\.go$]
          - id: validate-toml
          - id: no-go-testing
          - id: golangci-lint
          - id: go-critic
          - id: go-unit-tests
          - id: go-build
          - id: go-mod-tidy
