---
name: publish release

on:
    workflow_dispatch:
    release:
        types:
            - published
permissions: write-all

jobs:
    publish-docker-image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build the Docker image
              run: |-
                  docker build . --tag ghcr.io/kilianp07/simu:${{ github.event.release.name }}
                  docker push ghcr.io/kilianp07/simu:${{ github.event.release.name }}
    discord:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Discord notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              uses: Ilshidur/action-discord@master
              with:
                  args: '**Simu Release:** *${{ github.event.release.name }}* has been published by *${{ github.actor }}*'
